### ISSUE TITLE
[$50 in kSQT] Build starter project for Jackal Labs

### ISSUE THREAD

**Issue by siqi0408** [subquery/grants#52]
We require a starter project for Dymension with the following schema below. Check out https://github.com/subquery/cosmos-subql-starter  for examples of other Cosmos based starter projects for ideas.

The challenge will be to confirm the RPC endpoint, (there maybe some free ones available) and also to confirm the protobuf files (a Google search will help).

**RPC:**
http://167.142.158.242:36657/ (grpc is port 19090 and webgrpc is 19091)

**Protobuf:**
https://github.com/JackalLabs/canine-chain/tree/master/proto/canine_chain
 

**Schema:** 
type Transfers [@entity](https://github.com/entity) {
id: ID!
blockHeight: BigInt
txHash: String
fromAddress: String
toAddress: String
amount: String
denomination: String
}

**Explorer:**
https://www.jackallabs.io/

**important**
When you're done developing please make a PR to 
https://github.com/subquery/cosmos-subql-starter/pulls

**Comment by vvayffaring** [comment]
```
<StoreCache> ERROR Database transaction failed, rolling back Error: Invalid value { denom: 'ujkl', amount: '100000000' }
jackal-subquery-node-1   | 2023-11-03T08:09:06.252Z <worker #0> ERROR Uncaught Exception Error: Invalid value { denom: 'ujkl', amount: '100000000' }
jackal-subquery-node-1   | /usr/local/lib/node_modules/@subql/node-cosmos/node_modules/@subql/node-core/dist/indexer/worker/worker.js:130
jackal-subquery-node-1   |     throw e;
jackal-subquery-node-1   |     ^
jackal-subquery-node-1   | 
jackal-subquery-node-1   | Error: Invalid value { denom: 'ujkl', amount: '100000000' }
jackal-subquery-node-1   |     at escape (/usr/local/lib/node_modules/@subql/node-cosmos/node_modules/@subql/x-sequelize/lib/sql-string.js:53:11)
jackal-subquery-node-1   |     at Object.partialEscape [as escape] (/usr/local/lib/node_modules/@subql/node-cosmos/node_modules/@subql/x-sequelize/lib/sql-string.js:46:39)
jackal-subquery-node-1   |     at ABSTRACT.<anonymous> (/usr/local/lib/node_modules/@subql/node-cosmos/node_modules/@subql/x-sequelize/lib/dialects/postgres/data-types.js:389:22)
jackal-subquery-node-1   |     at Array.map (<anonymous>)
jackal-subquery-node-1   |     at ABSTRACT._value (/usr/local/lib/node_modules/@subql/node-cosmos/node_modules/@subql/x-sequelize/lib/dialects/postgres/data-types.js:379:19)
jackal-subquery-node-1   |     at ABSTRACT._stringify (/usr/local/lib/node_modules/@subql/node-cosmos/node_modules/@subql/x-sequelize/lib/dialects/postgres/data-types.js:393:29)
jackal-subquery-node-1   |     at ABSTRACT.stringify (/usr/local/lib/node_modules/@subql/node-cosmos/node_modules/@subql/x-sequelize/lib/data-types.js:22:19)
jackal-subquery-node-1   |     at Object.escape (/usr/local/lib/node_modules/@subql/node-cosmos/node_modules/@subql/x-sequelize/lib/sql-string.js:48:40)
jackal-subquery-node-1   |     at PostgresQueryGenerator.escape (/usr/local/lib/node_modules/@subql/node-cosmos/node_modules/@subql/x-sequelize/lib/dialects/abstract/query-generator.js:763:22)
jackal-subquery-node-1   |     at /usr/local/lib/node_modules/@subql/node-cosmos/node_modules/@subql/x-sequelize/lib/dialects/abstract/query-generator.js:259:21
jackal-subquery-node-1   | 
```
my repo https://github.com/vvayffaring/jackal

**Comment by jamesbayly** [comment]
@vvayffaring can you please make a PR to https://github.com/subquery/cosmos-subql-starter/pulls

**Comment by vvayffaring** [comment]
@jamesbayly done

**Comment by jamesbayly** [comment]
@siqi0408  please arrange the rewards
